//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_OODB_Laundry_GroupH
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeaderTransaction()
        {
            this.DetailTransaction = new HashSet<DetailTransaction>();
        }
    
        public string TransactionID { get; set; }
        public string UserID { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTransaction> DetailTransaction { get; set; }
        public virtual Users Users { get; set; }
    }
}
